### ISSUE TITLE
Condizione per determinare la presenza di più delimitatori e delimitatori lunghi

### ISSUE THREAD

**Issue by dario-campagna** [software-development-methods-19-20/string-calculator-elisavitale#1]
https://github.com/software-development-methods-19-20/string-calculator-elisavitale/blob/f975c60a5761c9d0e46a5d397d3bb2a73d48d8d5/production/source/dssc/calculator/StringCalculator.java#L93

Cosa accade con la stringa ```"//[\n2[2"```?

**Comment by elisavitale** [comment]
Con il codice scritto così com'è, il test della stringa `"//[\n2[2"` fallisce. Per risolvere il problema è stato sufficiente cambiare l'OR `||` in un AND `&&`. Non l'avevo notato... grazie!
