### ISSUE TITLE
String and String[]

### ISSUE THREAD

**Issue by dario-campagna** [software-development-methods-19-20/string-calculator-elisavitale#3]
https://github.com/software-development-methods-19-20/string-calculator-elisavitale/blob/f975c60a5761c9d0e46a5d397d3bb2a73d48d8d5/production/source/dssc/calculator/StringCalculator.java#L3

Il codice di questa classe è sufficientemente espressivo e leggibile. In particolare grazie al fatto che i metodi sono piccoli. L'espressività potrebbe migliorare riducendo l'uso di String e String[].

Quasi tutti i metodi lavorano con stringhe e array di stringhe. Due metodi costruiscono una nuova stringa e poi utilizzano il metodo ```split``` per ottenere un array di stringhe. Possiamo ottenere lo stesso risultato in modo diverso? Perché non costruire direttamente un array o una lista di stringhe?

Le stringhe vengono convertite in due diversi metodi. Il codice potrebbe essere più espressivo convertendo una volta sola le stringhe in interi e lavorando poi su essi? In che modo possono esserci utili gli Stream?

**Comment by elisavitale** [comment]
Ho rivisto il codice cercando di migliorarne l'espressività, le modifiche sono visibili in questo [commit](https://github.com/software-development-methods-19-20/string-calculator-elisavitale/commit/1fc994b622c354217738f0017a0175c85ef3f2e2#).
